# Generated by Django 4.0.1 on 2022-01-19 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_memory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='guests',
            field=models.ManyToManyField(blank=True, null=True, related_name='guests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memory',
            name='owners',
            field=models.ManyToManyField(blank=True, null=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
