# Generated by Django 4.0.1 on 2022-01-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_memory_guests_alter_memory_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='letter_avatar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
