# Generated by Django 4.0.1 on 2022-01-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_letter_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='letter_avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
