# Generated by Django 4.0.1 on 2022-01-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_letter_avatar_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
