# Generated by Django 4.0.1 on 2022-01-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_memory_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='images',
            new_name='image',
        ),
    ]
