# Generated by Django 4.0.1 on 2022-01-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_images_memory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='guests',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='owners',
        ),
        migrations.AddField(
            model_name='memory',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memory',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='shared', to=settings.AUTH_USER_MODEL),
        ),
    ]
