# Generated by Django 4.0.1 on 2022-01-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_memory_guests_remove_memory_owners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
