# Generated by Django 4.0.1 on 2022-01-22 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_memory_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.memory')),
            ],
        ),
    ]
