# Generated by Django 4.0.1 on 2022-01-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_memory_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
