# Generated by Django 4.0.1 on 2022-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_memory_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
