# Generated by Django 4.0.1 on 2022-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_memory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='images',
        ),
        migrations.AddField(
            model_name='memory',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
