# Generated by Django 4.0.1 on 2022-01-25 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_memoryspace_memory_memory_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryspace',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
