# Generated by Django 4.0.1 on 2022-01-26 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
