# Generated by Django 4.0.1 on 2022-01-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_memoryspace_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryspace',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='username_min_length',
        ),
    ]
