# Generated by Django 4.0.1 on 2022-02-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_memoryspace_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='memory',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
