# Generated by Django 4.0.1 on 2022-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_memoryspace_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
